import { Inter } from "next/font/google";
import { Navbar } from "./components/navbar";
import "./globals.css";
import ContextProvider from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "App",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Navbar />
          <div className="content">{children}</div>
        </ContextProvider>
      </body>
    </html>
  );
}
